// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: resources/mailer/access.proto

package mailer

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Access with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Access) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Access with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AccessMultiError, or nil if none found.
func (m *Access) ValidateAll() error {
	return m.validate(true)
}

func (m *Access) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetJobs()) > 20 {
		err := AccessValidationError{
			field:  "Jobs",
			reason: "value must contain no more than 20 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetJobs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AccessValidationError{
						field:  fmt.Sprintf("Jobs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AccessValidationError{
						field:  fmt.Sprintf("Jobs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AccessValidationError{
					field:  fmt.Sprintf("Jobs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(m.GetUsers()) > 20 {
		err := AccessValidationError{
			field:  "Users",
			reason: "value must contain no more than 20 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetUsers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AccessValidationError{
						field:  fmt.Sprintf("Users[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AccessValidationError{
						field:  fmt.Sprintf("Users[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AccessValidationError{
					field:  fmt.Sprintf("Users[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(m.GetQualifications()) > 20 {
		err := AccessValidationError{
			field:  "Qualifications",
			reason: "value must contain no more than 20 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetQualifications() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AccessValidationError{
						field:  fmt.Sprintf("Qualifications[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AccessValidationError{
						field:  fmt.Sprintf("Qualifications[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AccessValidationError{
					field:  fmt.Sprintf("Qualifications[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AccessMultiError(errors)
	}

	return nil
}

// AccessMultiError is an error wrapping multiple validation errors returned by
// Access.ValidateAll() if the designated constraints aren't met.
type AccessMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AccessMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AccessMultiError) AllErrors() []error { return m }

// AccessValidationError is the validation error returned by Access.Validate if
// the designated constraints aren't met.
type AccessValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessValidationError) ErrorName() string { return "AccessValidationError" }

// Error satisfies the builtin error interface
func (e AccessValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccess.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessValidationError{}

// Validate checks the field values on JobAccess with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *JobAccess) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JobAccess with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in JobAccessMultiError, or nil
// if none found.
func (m *JobAccess) ValidateAll() error {
	return m.validate(true)
}

func (m *JobAccess) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TargetId

	if utf8.RuneCountInString(m.GetJob()) > 20 {
		err := JobAccessValidationError{
			field:  "Job",
			reason: "value length must be at most 20 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetMinimumGrade() < 0 {
		err := JobAccessValidationError{
			field:  "MinimumGrade",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := AccessLevel_name[int32(m.GetAccess())]; !ok {
		err := JobAccessValidationError{
			field:  "Access",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.CreatedAt != nil {

		if all {
			switch v := interface{}(m.GetCreatedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, JobAccessValidationError{
						field:  "CreatedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, JobAccessValidationError{
						field:  "CreatedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return JobAccessValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.JobLabel != nil {

		if utf8.RuneCountInString(m.GetJobLabel()) > 50 {
			err := JobAccessValidationError{
				field:  "JobLabel",
				reason: "value length must be at most 50 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.JobGradeLabel != nil {

		if utf8.RuneCountInString(m.GetJobGradeLabel()) > 50 {
			err := JobAccessValidationError{
				field:  "JobGradeLabel",
				reason: "value length must be at most 50 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return JobAccessMultiError(errors)
	}

	return nil
}

// JobAccessMultiError is an error wrapping multiple validation errors returned
// by JobAccess.ValidateAll() if the designated constraints aren't met.
type JobAccessMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JobAccessMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JobAccessMultiError) AllErrors() []error { return m }

// JobAccessValidationError is the validation error returned by
// JobAccess.Validate if the designated constraints aren't met.
type JobAccessValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JobAccessValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JobAccessValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JobAccessValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JobAccessValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JobAccessValidationError) ErrorName() string { return "JobAccessValidationError" }

// Error satisfies the builtin error interface
func (e JobAccessValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJobAccess.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JobAccessValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JobAccessValidationError{}

// Validate checks the field values on UserAccess with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserAccess) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserAccess with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserAccessMultiError, or
// nil if none found.
func (m *UserAccess) ValidateAll() error {
	return m.validate(true)
}

func (m *UserAccess) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TargetId

	if m.GetUserId() < 0 {
		err := UserAccessValidationError{
			field:  "UserId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := AccessLevel_name[int32(m.GetAccess())]; !ok {
		err := UserAccessValidationError{
			field:  "Access",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.CreatedAt != nil {

		if all {
			switch v := interface{}(m.GetCreatedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserAccessValidationError{
						field:  "CreatedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserAccessValidationError{
						field:  "CreatedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserAccessValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.User != nil {

		if all {
			switch v := interface{}(m.GetUser()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserAccessValidationError{
						field:  "User",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserAccessValidationError{
						field:  "User",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserAccessValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UserAccessMultiError(errors)
	}

	return nil
}

// UserAccessMultiError is an error wrapping multiple validation errors
// returned by UserAccess.ValidateAll() if the designated constraints aren't met.
type UserAccessMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserAccessMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserAccessMultiError) AllErrors() []error { return m }

// UserAccessValidationError is the validation error returned by
// UserAccess.Validate if the designated constraints aren't met.
type UserAccessValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserAccessValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserAccessValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserAccessValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserAccessValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserAccessValidationError) ErrorName() string { return "UserAccessValidationError" }

// Error satisfies the builtin error interface
func (e UserAccessValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserAccess.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserAccessValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserAccessValidationError{}

// Validate checks the field values on QualificationAccess with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QualificationAccess) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QualificationAccess with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QualificationAccessMultiError, or nil if none found.
func (m *QualificationAccess) ValidateAll() error {
	return m.validate(true)
}

func (m *QualificationAccess) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TargetId

	// no validation rules for QualificationId

	if _, ok := AccessLevel_name[int32(m.GetAccess())]; !ok {
		err := QualificationAccessValidationError{
			field:  "Access",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.CreatedAt != nil {

		if all {
			switch v := interface{}(m.GetCreatedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QualificationAccessValidationError{
						field:  "CreatedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QualificationAccessValidationError{
						field:  "CreatedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QualificationAccessValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Qualification != nil {

		if all {
			switch v := interface{}(m.GetQualification()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QualificationAccessValidationError{
						field:  "Qualification",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QualificationAccessValidationError{
						field:  "Qualification",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetQualification()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QualificationAccessValidationError{
					field:  "Qualification",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return QualificationAccessMultiError(errors)
	}

	return nil
}

// QualificationAccessMultiError is an error wrapping multiple validation
// errors returned by QualificationAccess.ValidateAll() if the designated
// constraints aren't met.
type QualificationAccessMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QualificationAccessMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QualificationAccessMultiError) AllErrors() []error { return m }

// QualificationAccessValidationError is the validation error returned by
// QualificationAccess.Validate if the designated constraints aren't met.
type QualificationAccessValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QualificationAccessValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QualificationAccessValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QualificationAccessValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QualificationAccessValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QualificationAccessValidationError) ErrorName() string {
	return "QualificationAccessValidationError"
}

// Error satisfies the builtin error interface
func (e QualificationAccessValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQualificationAccess.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QualificationAccessValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QualificationAccessValidationError{}
