// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: resources/mailer/settings.proto

package mailer

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserSettings with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserSettings) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserSettings with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserSettingsMultiError, or
// nil if none found.
func (m *UserSettings) ValidateAll() error {
	return m.validate(true)
}

func (m *UserSettings) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() < 0 {
		err := UserSettingsValidationError{
			field:  "UserId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetBlockedUsers()) > 25 {
		err := UserSettingsValidationError{
			field:  "BlockedUsers",
			reason: "value must contain no more than 25 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetBlockedUsers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserSettingsValidationError{
						field:  fmt.Sprintf("BlockedUsers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserSettingsValidationError{
						field:  fmt.Sprintf("BlockedUsers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserSettingsValidationError{
					field:  fmt.Sprintf("BlockedUsers[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UserSettingsMultiError(errors)
	}

	return nil
}

// UserSettingsMultiError is an error wrapping multiple validation errors
// returned by UserSettings.ValidateAll() if the designated constraints aren't met.
type UserSettingsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserSettingsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserSettingsMultiError) AllErrors() []error { return m }

// UserSettingsValidationError is the validation error returned by
// UserSettings.Validate if the designated constraints aren't met.
type UserSettingsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserSettingsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserSettingsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserSettingsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserSettingsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserSettingsValidationError) ErrorName() string { return "UserSettingsValidationError" }

// Error satisfies the builtin error interface
func (e UserSettingsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserSettings.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserSettingsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserSettingsValidationError{}

// Validate checks the field values on BlockedUser with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BlockedUser) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BlockedUser with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BlockedUserMultiError, or
// nil if none found.
func (m *BlockedUser) ValidateAll() error {
	return m.validate(true)
}

func (m *BlockedUser) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if m.User != nil {

		if all {
			switch v := interface{}(m.GetUser()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BlockedUserValidationError{
						field:  "User",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BlockedUserValidationError{
						field:  "User",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BlockedUserValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BlockedUserMultiError(errors)
	}

	return nil
}

// BlockedUserMultiError is an error wrapping multiple validation errors
// returned by BlockedUser.ValidateAll() if the designated constraints aren't met.
type BlockedUserMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BlockedUserMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BlockedUserMultiError) AllErrors() []error { return m }

// BlockedUserValidationError is the validation error returned by
// BlockedUser.Validate if the designated constraints aren't met.
type BlockedUserValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BlockedUserValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BlockedUserValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BlockedUserValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BlockedUserValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BlockedUserValidationError) ErrorName() string { return "BlockedUserValidationError" }

// Error satisfies the builtin error interface
func (e BlockedUserValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBlockedUser.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BlockedUserValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BlockedUserValidationError{}
