// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: resources/documents/workflow.proto

package documents

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Workflow with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Workflow) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Workflow with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WorkflowMultiError, or nil
// if none found.
func (m *Workflow) ValidateAll() error {
	return m.validate(true)
}

func (m *Workflow) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Reminder

	if all {
		switch v := interface{}(m.GetReminders()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WorkflowValidationError{
					field:  "Reminders",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WorkflowValidationError{
					field:  "Reminders",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReminders()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WorkflowValidationError{
				field:  "Reminders",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AutoClose

	if all {
		switch v := interface{}(m.GetAutoCloseSettings()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WorkflowValidationError{
					field:  "AutoCloseSettings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WorkflowValidationError{
					field:  "AutoCloseSettings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAutoCloseSettings()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WorkflowValidationError{
				field:  "AutoCloseSettings",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WorkflowMultiError(errors)
	}

	return nil
}

// WorkflowMultiError is an error wrapping multiple validation errors returned
// by Workflow.ValidateAll() if the designated constraints aren't met.
type WorkflowMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkflowMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkflowMultiError) AllErrors() []error { return m }

// WorkflowValidationError is the validation error returned by
// Workflow.Validate if the designated constraints aren't met.
type WorkflowValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkflowValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkflowValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkflowValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkflowValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkflowValidationError) ErrorName() string { return "WorkflowValidationError" }

// Error satisfies the builtin error interface
func (e WorkflowValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkflow.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkflowValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkflowValidationError{}

// Validate checks the field values on Reminders with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Reminders) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Reminders with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RemindersMultiError, or nil
// if none found.
func (m *Reminders) ValidateAll() error {
	return m.validate(true)
}

func (m *Reminders) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetReminders()) > 3 {
		err := RemindersValidationError{
			field:  "Reminders",
			reason: "value must contain no more than 3 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetReminders() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RemindersValidationError{
						field:  fmt.Sprintf("Reminders[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RemindersValidationError{
						field:  fmt.Sprintf("Reminders[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RemindersValidationError{
					field:  fmt.Sprintf("Reminders[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return RemindersMultiError(errors)
	}

	return nil
}

// RemindersMultiError is an error wrapping multiple validation errors returned
// by Reminders.ValidateAll() if the designated constraints aren't met.
type RemindersMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemindersMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemindersMultiError) AllErrors() []error { return m }

// RemindersValidationError is the validation error returned by
// Reminders.Validate if the designated constraints aren't met.
type RemindersValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemindersValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemindersValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemindersValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemindersValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemindersValidationError) ErrorName() string { return "RemindersValidationError" }

// Error satisfies the builtin error interface
func (e RemindersValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReminders.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemindersValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemindersValidationError{}

// Validate checks the field values on Reminder with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Reminder) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Reminder with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReminderMultiError, or nil
// if none found.
func (m *Reminder) ValidateAll() error {
	return m.validate(true)
}

func (m *Reminder) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDuration() == nil {
		err := ReminderValidationError{
			field:  "Duration",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if d := m.GetDuration(); d != nil {
		dur, err := d.AsDuration(), d.CheckValid()
		if err != nil {
			err = ReminderValidationError{
				field:  "Duration",
				reason: "value is not a valid duration",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {

			lt := time.Duration(7776000*time.Second + 0*time.Nanosecond)
			gte := time.Duration(86400*time.Second + 0*time.Nanosecond)

			if dur < gte || dur >= lt {
				err := ReminderValidationError{
					field:  "Duration",
					reason: "value must be inside range [24h0m0s, 2160h0m0s)",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(m.GetMessage()) > 1024 {
		err := ReminderValidationError{
			field:  "Message",
			reason: "value length must be at most 1024 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ReminderMultiError(errors)
	}

	return nil
}

// ReminderMultiError is an error wrapping multiple validation errors returned
// by Reminder.ValidateAll() if the designated constraints aren't met.
type ReminderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReminderMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReminderMultiError) AllErrors() []error { return m }

// ReminderValidationError is the validation error returned by
// Reminder.Validate if the designated constraints aren't met.
type ReminderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReminderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReminderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReminderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReminderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReminderValidationError) ErrorName() string { return "ReminderValidationError" }

// Error satisfies the builtin error interface
func (e ReminderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReminder.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReminderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReminderValidationError{}

// Validate checks the field values on AutoClose with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AutoClose) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AutoClose with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AutoCloseMultiError, or nil
// if none found.
func (m *AutoClose) ValidateAll() error {
	return m.validate(true)
}

func (m *AutoClose) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDuration() == nil {
		err := AutoCloseValidationError{
			field:  "Duration",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if d := m.GetDuration(); d != nil {
		dur, err := d.AsDuration(), d.CheckValid()
		if err != nil {
			err = AutoCloseValidationError{
				field:  "Duration",
				reason: "value is not a valid duration",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {

			lt := time.Duration(7776000*time.Second + 0*time.Nanosecond)
			gte := time.Duration(86400*time.Second + 0*time.Nanosecond)

			if dur < gte || dur >= lt {
				err := AutoCloseValidationError{
					field:  "Duration",
					reason: "value must be inside range [24h0m0s, 2160h0m0s)",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(m.GetMessage()) > 1024 {
		err := AutoCloseValidationError{
			field:  "Message",
			reason: "value length must be at most 1024 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AutoCloseMultiError(errors)
	}

	return nil
}

// AutoCloseMultiError is an error wrapping multiple validation errors returned
// by AutoClose.ValidateAll() if the designated constraints aren't met.
type AutoCloseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AutoCloseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AutoCloseMultiError) AllErrors() []error { return m }

// AutoCloseValidationError is the validation error returned by
// AutoClose.Validate if the designated constraints aren't met.
type AutoCloseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AutoCloseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AutoCloseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AutoCloseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AutoCloseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AutoCloseValidationError) ErrorName() string { return "AutoCloseValidationError" }

// Error satisfies the builtin error interface
func (e AutoCloseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAutoClose.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AutoCloseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AutoCloseValidationError{}

// Validate checks the field values on WorkflowCronData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WorkflowCronData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WorkflowCronData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WorkflowCronDataMultiError, or nil if none found.
func (m *WorkflowCronData) ValidateAll() error {
	return m.validate(true)
}

func (m *WorkflowCronData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LastDocId

	if len(errors) > 0 {
		return WorkflowCronDataMultiError(errors)
	}

	return nil
}

// WorkflowCronDataMultiError is an error wrapping multiple validation errors
// returned by WorkflowCronData.ValidateAll() if the designated constraints
// aren't met.
type WorkflowCronDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkflowCronDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkflowCronDataMultiError) AllErrors() []error { return m }

// WorkflowCronDataValidationError is the validation error returned by
// WorkflowCronData.Validate if the designated constraints aren't met.
type WorkflowCronDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkflowCronDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkflowCronDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkflowCronDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkflowCronDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkflowCronDataValidationError) ErrorName() string { return "WorkflowCronDataValidationError" }

// Error satisfies the builtin error interface
func (e WorkflowCronDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkflowCronData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkflowCronDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkflowCronDataValidationError{}

// Validate checks the field values on WorkflowState with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WorkflowState) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WorkflowState with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WorkflowStateMultiError, or
// nil if none found.
func (m *WorkflowState) ValidateAll() error {
	return m.validate(true)
}

func (m *WorkflowState) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DocumentId

	if m.NextReminderTime != nil {

		if all {
			switch v := interface{}(m.GetNextReminderTime()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WorkflowStateValidationError{
						field:  "NextReminderTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WorkflowStateValidationError{
						field:  "NextReminderTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetNextReminderTime()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WorkflowStateValidationError{
					field:  "NextReminderTime",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.NextReminderCount != nil {
		// no validation rules for NextReminderCount
	}

	if m.AutoCloseTime != nil {

		if all {
			switch v := interface{}(m.GetAutoCloseTime()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WorkflowStateValidationError{
						field:  "AutoCloseTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WorkflowStateValidationError{
						field:  "AutoCloseTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetAutoCloseTime()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WorkflowStateValidationError{
					field:  "AutoCloseTime",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Workflow != nil {

		if all {
			switch v := interface{}(m.GetWorkflow()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WorkflowStateValidationError{
						field:  "Workflow",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WorkflowStateValidationError{
						field:  "Workflow",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetWorkflow()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WorkflowStateValidationError{
					field:  "Workflow",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Document != nil {

		if all {
			switch v := interface{}(m.GetDocument()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WorkflowStateValidationError{
						field:  "Document",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WorkflowStateValidationError{
						field:  "Document",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDocument()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WorkflowStateValidationError{
					field:  "Document",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return WorkflowStateMultiError(errors)
	}

	return nil
}

// WorkflowStateMultiError is an error wrapping multiple validation errors
// returned by WorkflowState.ValidateAll() if the designated constraints
// aren't met.
type WorkflowStateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkflowStateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkflowStateMultiError) AllErrors() []error { return m }

// WorkflowStateValidationError is the validation error returned by
// WorkflowState.Validate if the designated constraints aren't met.
type WorkflowStateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkflowStateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkflowStateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkflowStateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkflowStateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkflowStateValidationError) ErrorName() string { return "WorkflowStateValidationError" }

// Error satisfies the builtin error interface
func (e WorkflowStateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkflowState.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkflowStateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkflowStateValidationError{}

// Validate checks the field values on WorkflowUserState with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WorkflowUserState) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WorkflowUserState with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WorkflowUserStateMultiError, or nil if none found.
func (m *WorkflowUserState) ValidateAll() error {
	return m.validate(true)
}

func (m *WorkflowUserState) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DocumentId

	if m.GetUserId() <= 0 {
		err := WorkflowUserStateValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.ManualReminderTime != nil {

		if all {
			switch v := interface{}(m.GetManualReminderTime()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WorkflowUserStateValidationError{
						field:  "ManualReminderTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WorkflowUserStateValidationError{
						field:  "ManualReminderTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetManualReminderTime()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WorkflowUserStateValidationError{
					field:  "ManualReminderTime",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.ManualReminderMessage != nil {
		// no validation rules for ManualReminderMessage
	}

	if m.Workflow != nil {

		if all {
			switch v := interface{}(m.GetWorkflow()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WorkflowUserStateValidationError{
						field:  "Workflow",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WorkflowUserStateValidationError{
						field:  "Workflow",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetWorkflow()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WorkflowUserStateValidationError{
					field:  "Workflow",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Document != nil {

		if all {
			switch v := interface{}(m.GetDocument()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WorkflowUserStateValidationError{
						field:  "Document",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WorkflowUserStateValidationError{
						field:  "Document",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDocument()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WorkflowUserStateValidationError{
					field:  "Document",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return WorkflowUserStateMultiError(errors)
	}

	return nil
}

// WorkflowUserStateMultiError is an error wrapping multiple validation errors
// returned by WorkflowUserState.ValidateAll() if the designated constraints
// aren't met.
type WorkflowUserStateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkflowUserStateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkflowUserStateMultiError) AllErrors() []error { return m }

// WorkflowUserStateValidationError is the validation error returned by
// WorkflowUserState.Validate if the designated constraints aren't met.
type WorkflowUserStateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkflowUserStateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkflowUserStateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkflowUserStateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkflowUserStateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkflowUserStateValidationError) ErrorName() string {
	return "WorkflowUserStateValidationError"
}

// Error satisfies the builtin error interface
func (e WorkflowUserStateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkflowUserState.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkflowUserStateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkflowUserStateValidationError{}
